"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
const scenes=[['One studio. Many possibilities.','A MackProjekt connects technology, creative identity, and community ventures.'],['Build the systems.','Enterprise platforms. Connected care. People at the center.'],['Move the culture.','KingMe. QueenMe. Mi Minks. Stories into action.'],['Make your next Projekt.','Explore the work. Bring your vision. Build with AMP.']];
export function IntroTrigger({large=false}:{large?:boolean}){return <button className={large?'intro-cinema':'intro-trigger'} onClick={()=>window.dispatchEvent(new Event('amp-open-intro'))}>{large&&<img src="/brand/kingme.jpg" alt="" width="1000" height="650" loading="lazy"/>}<span className="intro-play-symbol" aria-hidden="true">▶</span><span>Watch the AMP introduction<small>Technology. Culture. Purpose.</small></span><span aria-hidden="true">↗</span></button>}
export function IntroVideo(){const dialog=useRef<HTMLDialogElement>(null);const video=useRef<HTMLVideoElement>(null);const [scene,setScene]=useState(0);const [open,setOpen]=useState(false);const returnFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{const show=()=>{returnFocus.current=document.activeElement as HTMLElement;setOpen(true);};window.addEventListener('amp-open-intro',show);return()=>window.removeEventListener('amp-open-intro',show);},[]);
 useEffect(()=>{if(!open)return;const d=dialog.current;d?.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';setScene(0);if(video.current){video.current.currentTime=0;void video.current.play().catch(()=>{});}return()=>{video.current?.pause();d?.close();document.body.style.overflow=before;returnFocus.current?.focus();};},[open]);
 return <dialog ref={dialog} className="intro-dialog" aria-label="Introduction to A MackProjekt" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><div className="intro-dialog-top"><span>A MACKPROJEKT / THE INTRODUCTION</span><button onClick={()=>setOpen(false)} aria-label="Close introduction">Close ×</button></div><div className="intro-screen"><video ref={video} playsInline muted controls preload="none" poster="/brand/amp-logo.jpg" onTimeUpdate={e=>{const v=e.currentTarget;setScene(Math.min(3,Math.floor((v.currentTime/(v.duration||10))*4)));}}><source src="/brand/mackprojekt-highlight.mp4" type="video/mp4"/></video><div className="intro-caption" aria-hidden="true"><span>0{scene+1} / 04</span><h2>{scenes[scene][0]}</h2><p>{scenes[scene][1]}</p></div></div><div className="intro-dialog-bottom"><Link href="/innovation" onClick={()=>setOpen(false)} className="amp-text-link">Explore the work ↗</Link><Link href="/interest" onClick={()=>setOpen(false)} className="amp-button">Start a Projekt ↗</Link></div><details className="intro-transcript"><summary>Read the introduction</summary>{scenes.map(([title,text])=><p key={title}><strong>{title}</strong> {text}</p>)}</details></dialog>
}
