"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
const scenes=[
 {start:0,label:'AMP',title:'One studio. Many possibilities.',text:'Technology. Creative identity. Community. Meet A MackProjekt.'},
 {start:10,label:'Dashboards',title:'See the bigger picture.',text:'Inside the staff operations hub: team, caseload, and next actions. Actual portal UI, demo data.'},
 {start:15,label:'Case management',title:'Every case. In context.',text:'A clear view of the participant roster, capacity, and case status. Actual portal UI, demo data.'},
 {start:20,label:'Learning',title:'Keep moving forward.',text:'Explore professional development, courses, and training records. Actual portal UI, demo data.'},
 {start:25,label:'Coordination',title:'Make the next move together.',text:'Schedules, team meetings, and workflow tools in one view. Actual portal UI, demo data.'},
];
export function IntroTrigger({large=false}:{large?:boolean}){return <button className={large?'intro-cinema':'intro-trigger'} onClick={()=>window.dispatchEvent(new Event('amp-open-intro'))}>{large&&<img src="/brand/portal-dashboard.webp" alt="" width="1280" height="721" loading="lazy"/>}<span className="intro-play-symbol" aria-hidden="true">▶</span><span>Watch the AMP introduction<small>30 seconds. Inside the portals.</small></span><span aria-hidden="true">↗</span></button>}
export function IntroVideo(){
 const dialog=useRef<HTMLDialogElement>(null);const video=useRef<HTMLVideoElement>(null);const [scene,setScene]=useState(0);const [open,setOpen]=useState(false);const [ready,setReady]=useState(false);const [loadError,setLoadError]=useState(false);const returnFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{const show=()=>{returnFocus.current=document.activeElement as HTMLElement;setOpen(true);};window.addEventListener('amp-open-intro',show);return()=>window.removeEventListener('amp-open-intro',show);},[]);
 useEffect(()=>{if(!open)return;const d=dialog.current;const player=video.current;const controller=new AbortController();let objectUrl:string|undefined;d?.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';setScene(0);setReady(false);setLoadError(false);
 // Load the small film on demand so every chapter can seek without another network request.
 void fetch('/brand/amp-portal-intro.mp4',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Video unavailable');return r.blob();}).then(blob=>{if(controller.signal.aborted||!player)return;objectUrl=URL.createObjectURL(blob);player.src=objectUrl;player.load();setReady(true);void player.play().catch(()=>{});}).catch(()=>{if(!controller.signal.aborted)setLoadError(true);});
 return()=>{controller.abort();player?.pause();if(player){player.removeAttribute('src');player.load();}if(objectUrl)URL.revokeObjectURL(objectUrl);d?.close();document.body.style.overflow=before;returnFocus.current?.focus();};},[open]);
 return <dialog ref={dialog} className="intro-dialog" aria-label="Introduction to A MackProjekt" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><div className="intro-dialog-top"><span>A MACKPROJEKT / INSIDE THE PORTALS</span><button onClick={()=>setOpen(false)} aria-label="Close introduction">Close ×</button></div><div className="intro-screen"><video ref={video} playsInline muted controls preload="none" poster="/brand/portal-dashboard.webp" aria-label="30-second AMP introduction with portal highlights" onTimeUpdate={e=>{const time=e.currentTarget.currentTime;setScene(scenes.reduce((current,s,i)=>time>=s.start?i:current,0));}}></video></div>{!ready&&<p role="status">{loadError?"The introduction could not load. Please close and reopen to retry.":"Loading the portal introduction…"}</p>}<div className="intro-caption"><span>0{scene+1} / 05</span><h2>{scenes[scene].title}</h2><p>{scenes[scene].text}</p></div><div className="intro-chapters" aria-label="Video chapters">{scenes.map((s,i)=><button key={s.label} disabled={!ready} aria-pressed={scene===i} onClick={()=>{if(video.current){video.current.currentTime=s.start;setScene(i);}}}>{s.label}</button>)}</div><div className="intro-dialog-bottom"><Link href="/innovation" onClick={()=>setOpen(false)} className="amp-text-link">Explore the work ↗</Link><Link href="/interest" onClick={()=>setOpen(false)} className="amp-button">Start a Projekt ↗</Link></div><details className="intro-transcript"><summary>Read the introduction</summary>{scenes.map(s=><p key={s.label}><strong>{s.title}</strong> {s.text}</p>)}</details></dialog>;
}
