"use client";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { RoomEnvironment } from "three/addons/environments/RoomEnvironment.js";
export function Sculpture({kind}:{kind:"amp"|"king"|"queen"}){
 const host=useRef<HTMLDivElement>(null);const [ready,setReady]=useState(false);
 useEffect(()=>{const container=host.current;if(!container)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return;}
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,.45,6.5);camera.lookAt(0,0,0);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0x000000,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;container.appendChild(renderer.domElement);
 const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();scene.add(new THREE.AmbientLight(0xffffff,1.4));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(2,4,4);scene.add(light);const edge=new THREE.DirectionalLight(kind==='amp'?0x3ce8f2:0xffd88a,3);edge.position.set(-3,1,2);scene.add(edge);
 const group=new THREE.Group();scene.add(group);const metal=new THREE.MeshStandardMaterial({color:kind==='amp'?0x30c6d4:kind==='king'?0xbd8833:0xc77b9c,metalness:.86,roughness:.19});const silver=new THREE.MeshStandardMaterial({color:0xdce5e4,metalness:.95,roughness:.17});const dark=new THREE.MeshStandardMaterial({color:0x142d3a,metalness:.7,roughness:.25});
 if(kind==='amp'){
 const shape=new THREE.Shape();shape.moveTo(-1,-1.15);shape.lineTo(.0,1.5);shape.lineTo(1.1,-.6);shape.lineTo(.69,-.37);shape.lineTo(.04,.83);shape.lineTo(-.56,-.82);shape.lineTo(.41,-.1);shape.lineTo(.65,-.51);shape.lineTo(-1,-1.15);const geo=new THREE.ExtrudeGeometry(shape,{depth:.27,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.065,bevelThickness:.06});geo.center();group.add(new THREE.Mesh(geo,metal));const ring=new THREE.Mesh(new THREE.TorusGeometry(1.67,.025,12,96),silver);ring.rotation.set(.45,.65,.18);group.add(ring);const ring2=new THREE.Mesh(new THREE.TorusGeometry(1.87,.012,8,96),metal);ring2.rotation.set(1.1,-.3,.3);group.add(ring2);for(let i=0;i<3;i++){const node=new THREE.Mesh(new THREE.SphereGeometry(.08,16,16),silver);node.position.set(Math.cos(i*2.1)*1.67,Math.sin(i*2.1)*1.67,0);group.add(node);}group.rotation.set(-.08,-.3,-.1);
 }else{
 const profile=[[0,-1.5],[.75,-1.5],[.8,-1.39],[.76,-1.23],[.59,-1.12],[.54,-1.02],[.39,-.96],[.24,-.45],[.21,.10],[.42,.24],[.44,.36],[.32,.48],[.4,.65],[.51,.82],[.54,1.04],[.39,1.12],[0,1.12]].map(([x,y])=>new THREE.Vector2(x,y));group.add(new THREE.Mesh(new THREE.LatheGeometry(profile,64),metal));const rim=new THREE.Mesh(new THREE.TorusGeometry(.53,.055,12,64),silver);rim.rotation.x=Math.PI/2;rim.position.y=1.02;group.add(rim);
 if(kind==='king'){const vertical=new THREE.Mesh(new THREE.BoxGeometry(.13,.6,.15),silver);vertical.position.y=1.35;group.add(vertical);const cross=new THREE.Mesh(new THREE.BoxGeometry(.46,.12,.15),silver);cross.position.y=1.43;group.add(cross);}else{for(let i=0;i<7;i++){const a=i*Math.PI*2/7;const tip=new THREE.Mesh(new THREE.ConeGeometry(.075,.38,12),silver);tip.position.set(Math.cos(a)*.43,1.24,Math.sin(a)*.43);group.add(tip);const gem=new THREE.Mesh(new THREE.SphereGeometry(.065,12,12),metal);gem.position.set(Math.cos(a)*.43,1.45,Math.sin(a)*.43);group.add(gem);}}
 const base=new THREE.Mesh(new THREE.CylinderGeometry(.91,1,.13,64),dark);base.position.y=-1.64;group.add(base);group.rotation.y=-.4;group.rotation.z=.08;
 }
 let pointerX=0,pointerY=0,visible=false,frame=0,last=0,t=0;const media=matchMedia('(prefers-reduced-motion: reduce)');const pointer=(e:PointerEvent)=>{const r=container.getBoundingClientRect();pointerX=((e.clientX-r.left)/r.width-.5)*.8;pointerY=((e.clientY-r.top)/r.height-.5)*.25;};const leave=()=>{pointerX=0;pointerY=0;};container.addEventListener('pointermove',pointer);container.addEventListener('pointerleave',leave);
 const resize=()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(container);resize();const io=new IntersectionObserver(es=>{visible=es[0].isIntersecting;});io.observe(container);renderer.render(scene,camera);setReady(true);
 const tick=(now:number)=>{const dt=Math.min(now-last,40);last=now;if(visible&&!document.hidden){const paused=media.matches||document.documentElement.dataset.ampMotion==='paused';if(!paused)t+=dt*.001;const y=paused?-.3:Math.sin(t*.35)*.3+pointerX-.3;group.rotation.y+=(y-group.rotation.y)*.06;group.rotation.x+=((paused?0:pointerY)-group.rotation.x)*.05;if(!paused)group.position.y=Math.sin(t*.7)*.065;renderer.render(scene,camera);}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
 const lost=(e:Event)=>{e.preventDefault();setReady(false);};renderer.domElement.addEventListener('webglcontextlost',lost);
 return()=>{cancelAnimationFrame(frame);io.disconnect();ro.disconnect();container.removeEventListener('pointermove',pointer);container.removeEventListener('pointerleave',leave);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();}});metal.dispose();silver.dispose();dark.dispose();env.dispose();renderer.dispose();renderer.domElement.remove();};
 },[kind]);
 return <div className={'amp-sculpture '+(ready?'sculpture-ready':'')} ref={host} role="img" aria-label={kind==='amp'?'Animated AMP-inspired three-dimensional sculpture':`Animated ${kind} chess sculpture`}><img className="sculpture-fallback" src={kind==='amp'?'/brand/projekt-enterprise-icon.svg':kind==='king'?'/brand/kingme.jpg':'/brand/queenme.png'} alt="" width="500" height="500" loading="lazy"/></div>;
}
